### ISSUE TITLE
Not a subset of JSON

### ISSUE THREAD

**Issue by dtolnay** [vtduncan/canonical_json#1]
> Canonical JSON is a subset of JSON in which values each have a single, unambiguous serialized form.

> Canonical JSON is parsable with any full JSON parser.

Neither of those is true if you have a string containing control characters:

```rust
extern crate canonical_json;
extern crate serde_json;

fn main() {
    let j = "\"\0\"";
    assert!(canonical_json::from_str::<String>(j).is_ok());
    assert!(serde_json::from_str::<String>(j).is_err());
}
```

Is this a bug in the documentation or a bug in the implementation?

**Comment by vtduncan** [comment]
Thank you very much for the bug report and example! This was a bug in the docs.

61286d7
