### ISSUE TITLE
Update to Serde 1.0

### ISSUE THREAD

**Issue by dtolnay** [vtduncan/canonical_json#3]
Release notes for 0.9.0: https://github.com/serde-rs/serde/releases/tag/v0.9.0
Release notes for 1.0.0: https://github.com/serde-rs/serde/releases/tag/v1.0.0

**Comment by vtduncan** [comment]
Hi @dtolnay! Thanks for working on Serde as always, and especially for your very nice release notes and new documentation. Congratulations on 1.0 :tada:!

I'm working through the changes to bring this in line with the new serde_json.

**Comment by vtduncan** [comment]
After a few attempts at doing this upgrade I wasn't able to find a way where I was satisfied with the quality and parts of the implementation.

Because I'm no longer using this library I'm going to leave it for now.

Still, I appreciate the notification about the new versions. Thank you.
